### M1 T01: Pràctica amb programació numèrica NumPy
Carla Toledo Rodríguez

**Exercici 1**
Crea una funció que donat un Array d’una dimensió, et faci un resum estadístic bàsic de les dades. Si detecta que l’array té més d’una dimensió, ha de mostrar un missatge d’error.

In [2]:
# Importem la llibreria "numpy"
import numpy as np

# Creem un array d'una dimensió i un altre de dos dimensions
array_a = np.array([5,8,6])
array_b = np.array([(2,1,9),(1,2,3)])

print(array_a)
print(array_b)

[5 8 6]
[[2 1 9]
 [1 2 3]]


In [2]:
# Associem l'array escollit amb la variable 
array1 = array_a
# array1 = array_b

# Creem les variables per l'anàlisi estadístic
dimensio = array1.shape
longitud = len(array1)
tipus_dada = array1.dtype
suma = array1.sum()
minim = array1.min()
maxim = array1.max()
mitjana = array1.mean()
mediana = np.median(array1)
coef_corr = np.corrcoef(array1)
desv_std = np.std(array1)

In [3]:
# La funció és:

def stats_array():
    if array1.ndim < 2:
        print("Dimensió: " + str(dimensio)) 
        print("Longitud: " + str(longitud))
        print("Tipus de dada: " + str(tipus_dada))
        print("Suma dels valors: " + str(suma))
        print("Valor mínim: " + str(minim))
        print("Valor màxim: " + str(maxim))
        print("Valor mitjà: " + str(mitjana))
        print("Coeficient de correlació: " + str(coef_corr))
        print("Desviació estàndar: " + str(desv_std)) 
    else:
        return "Error: l'array ha de tenir només una dimensió"

stats_array()

Dimensió: (3,)
Longitud: 3
Tipus de dada: int32
Suma dels valors: 19
Valor mínim: 5
Valor màxim: 8
Valor mitjà: 6.333333333333333
Coeficient de correlació: 1.0
Desviació estàndar: 1.247219128924647


**Exercici 2**
Crea una funció que et generi un quadrat NxN de nombres aleatoris entre el 0 i el 100.

In [5]:
# La funció conté la formula per generar un array 2D NxN de nombres aleatoris. En aquest cas, N=3

def random_array1():
    print(np.random.randint([(100,100,100),(100,100,100)]))

random_array1()

[[94 67 50]
 [47 83 63]]


In [6]:
# Solució

def matrix_generator():
    y = int(input('Tria un numero del 1 al 10: '))
    matriu_nxn = np.random.randint(1, 101, size = (y, y))
    return matriu_nxn

matrix_generator()

Tria un numero del 1 al 10: 4


array([[88, 38, 48, 66],
       [85, 33, 84, 68],
       [98, 37, 83, 12],
       [40, 42, 34, 36]])

**Exercici 3**
Crea una funció que donada una taula de dues dimensions, et calculi els totals per fila i els totals per columna.

In [10]:
# Creem un array de dos dimensions i un array d'una dimensió
array_c = np.array([(30,15,45),(44,71,20)])
array_d = np.array([23,8,12])

print(array_c)
print(array_d)

# Associem l'array escollit amb la variable 
array2 = array_c
#array2 = array_d

[[30 15 45]
 [44 71 20]]
[23  8 12]


In [11]:
# La funció és:

def calc_totals():
    if 1 < array2.ndim < 3:
        print('Els totals per fila són ' + str(array2.sum(axis=1)))
        print('Els totals per columna són ' + str(array2.sum(axis=0)))
        return array2
    else:
        return 'Error'

calc_totals()

Els totals per fila són [ 90 135]
Els totals per columna són [74 86 65]


array([[30, 15, 45],
       [44, 71, 20]])

In [12]:
# Solució

def matriu_generador():
    x = int(input('Tria un numero del 1 al 10 que serà el número de files: '))
    y = int(input('Tria un numero del 1 al 10 que serà el número de columnes: '))
    matriu_nxy = np.random.randint(1, 101, size = (x, y))
    print('Els totals per fila són {}'.format(np.sum(matriu_nxy, axis=1)))
    print('Els totals per columna són {}'.format(np.sum(matriu_nxy, axis=0)))
    return matriu_nxy

matriu_generador()

Tria un numero del 1 al 10 que serà el número de files: 2
Tria un numero del 1 al 10 que serà el número de columnes: 3
Els totals per fila són [244 162]
Els totals per columna són [103 188 115]


array([[79, 90, 75],
       [24, 98, 40]])

**Exercici 4**
Implementa manualment una funció que calculi el coeficient de correlació. Informa’t-en sobre els seus usos i interpretació.

El coeficient de correlació indica el grau de correlació entre dos variables quantitatives. A Estadística, és molt comú l'ús del coeficient de correlació de Pearson per a dades amb una distribució normal. També hi han altres correlacions com la de Spearman o Kendall.

El coeficient de correlació té la següent fórmula:

![coeficient](https://economipedia.com/wp-content/uploads/2015/12/formula-correlaci%C3%B3n.png)

És a dir, és la covariança entre el valor "x" i "y" (grau de variació conjunta entre dos variables), sobre la multiplicació de la desviació estàndar de "x" i la desviació estàndar de "y". D'aquesta manera, s'estandaritza la covariança.

El valor de p(x,y) es situa entre -1 i 1:
* Si el valor és < 0, la correlació és negativa.
* Si el valor és = 0, no hi ha relació entre les dues variables.
* Si el valor és > 0, la correlació es positiva.

Quan més proper estigui el valor als extrems [-1,1], més forta és la correlació. Si els valors són iguals a [-1,1], indica que existeix una relació lineal negativa/positiva perfecta.

In [7]:
# Definim dos arrays d'una dimensió

array_e = np.array([0.5,2,3,1])
array_f = np.array([2,3,2.9,1.5])

In [8]:
# Per extreure el numerador de la fracció, busquem la formula de la covariança:

cov_array = np.mean((array_e-np.mean(array_e))*(array_f-np.mean(array_f)))

In [9]:
# Utilitzem les funcions de la covariança cov() i desviació estàndar std() per crear la fórmula del coeficient de correlació

def coefcorr():
    print(cov_array / (np.std(array_e) * np.std(array_f)))

coefcorr()

0.800045880148271


In [10]:
# Comprovem amb la funció corrcoef(). El coeficient de correlació entre els dos arrays és força alt, igual a 0.8

np.corrcoef(array_e,array_f)

array([[1.        , 0.80004588],
       [0.80004588, 1.        ]])